### ISSUE TITLE
Can I customise the message

### ISSUE THREAD

**Issue by tomasherrera** [sachinchoolur/angular-flash#4]
I want to get rid off the "x" on the message, can I do it? I don't users to be able to close the message but instead, let it dismiss it self

**Comment by ramtml** [comment]
Hi,
You can just hide the close button via css.
``` css
.alert .close {
  display: none;
}
```
